Add linter, Add code html, css to Web-portfolio
Fernando426/Portfolio-mobile-website pull request #1
Opened 2023-04-29 12:30 UTC by Fernando426

-linters were added
-the files and the html and css code for the first section of the portpolio were created

2023-04-29 12:44 UTC, shella12 reviewed
Hi @Fernando426 , 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has linter errors please fix the linter errors before requesting for another review

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-29 21:07 UTC, V-Blaze requested changes
## Hi @Fernando426 , 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Readme looks professional✔
- Clean organized code👋 ✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 21:07 UTC, V-Blaze commented on index.html
> +        </ul>
- [ ] You did great using the header tag and also using the nav tag for your menu. :+1: :+1:  But I think there are still some improvements you need to make here.
- I'll suggest you wrap your logo in an `a` tag This is for three reasons: convention, semantics, and user experience(UX). :+1: :+1: 
- The logo image you used is broken, I'll suggest you fix this.
- Also the margin at the top of your menu is greater than the one in the provided design, I'll suggest you fix this as your portfolio is meant to look exactly like the Figma design. :+1: :100: 

- Screenshot for reference:
![Screenshot from 2023-04-29 21-31-42](https://user-images.githubusercontent.com/107632780/235323302-f9e5fb1d-27e1-461b-81b9-cb26d263e679.png)

2023-04-29 21:07 UTC, V-Blaze commented on index.html
> +  </header>
- [ ] I'll suggest moving this code into the `header` tag above, You are meant to only have one `header ` tag on your page. :+1:

2023-04-29 21:07 UTC, V-Blaze commented on index.html
> +  </section>
- [ ] You did great implementing this part of the design. :+1: :+1:  I also think there are some improvements you need to make here before moving to the next milestone.
- The spacing between your header and your title doesn't match the one in the given design. I'll suggest you check the margin and spacing and implement i=them acccoer=ingly in your project as part of the requirement is being able to replicate exactly the given design. :+1: :smile: 
- I'll also suggest increasing the font size of your title as it's slightly smaller than the provided design. :+1: 
- The content of your paragraph tends to overflow the page, I'll suggest you look into this too. :+1: :smile: 

- Your Design:
![Selection_025](https://user-images.githubusercontent.com/107632780/235323649-7f87b4f1-1fa0-4bf1-90b9-2bf810042622.png)

- Figma design:
![Selection_024](https://user-images.githubusercontent.com/107632780/235323670-2387f198-39cb-46d5-b485-2e1d0620f4e1.png)

2023-04-29 21:07 UTC, V-Blaze commented on index.html
> +    </div>
- [ ] Nice job adding the social images but I think there are some changes you need to make here. :+1: 
- The image links to the social icons are broken, and they are not currently displaying properly. I'll suggest you look into this as broken images are not good for the UI and optimal user experience. :+1: :100: 
- I'll suggest you use an `ul` tag here instead of a div and each image should be a `li` item. Also, I'll suggest wrapping the images in an `a` tag, apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href. :small_airplane: :smile: 


- Screenshot for reference:
![Screenshot from 2023-04-29 21-50-17](https://user-images.githubusercontent.com/107632780/235324044-05b1c940-6604-4231-b603-8c6b397339a8.png)

2023-04-29 21:07 UTC, V-Blaze commented on index.html
> +<body>
- [ ] I noticed there is a white space at the top and left part of your project which is not in the Figma design, I'll suggest you look into this and adjust your design properly. :+1: :smile: :100: 

SCREENSHOT FOR REFERENCE:
![Selection_026](https://user-images.githubusercontent.com/107632780/235324226-59fa430b-7c09-40ff-9e09-1b0627f425d2.png)

2023-04-30 04:11 UTC, didierganthier reviewed
Hi @Fernando426 ,

While you put in a lot of hard work in this project, unfortunately, I cannot proceed with the review of your code.

<img src="https://media.giphy.com/media/HOTfexLzbar5u/giphy.gif" />

## Invalid Code Review Request 🚫

- You have submitted a project with linters tests failing. ❌ 

Your Code Review Request will be marked as invalid in your Dashboard, but don't worry you can always try again! 💪

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

--------

_Invalid Code Review Request **does not count** towards the code reviews limit._

2023-04-30 05:08 UTC, taldr27 requested changes
## Hi @Fernando426, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![almost](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Incorporates feedback from previous code reviews.

 ## Required Changes ♻️
_Check the comments under the review._

------
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in @taldr27 your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-04-30 05:08 UTC, taldr27 commented on index.html
> +    </div>
- [ ] Great work on your project so far! I noticed a small issue that I think could be easily fixed. When viewing your page, I noticed that there is a lot of white space to the right of the page when scrolling horizontally. Upon further inspection, it seems that this issue is due to the fixed width of your headline content. Once you identify the problem area, adjusting the `width` of your headline content should fix the issue. Keep up the good work!👌

![image](https://user-images.githubusercontent.com/107952724/235336632-6fa7a132-1a04-419b-9858-dbf4122d5932.png)

```
Hint:
To help you visualize the issue, I recommend adding this CSS rule to your stylesheet to see all the elements with a border:
* {
  border: 1px solid red;
}
```

2023-04-30 06:59 UTC, Efiamotu-1 requested changes
Hi @Fernando426 , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive README
- ✔️ Descriptive PR title 
- The code is top-notch! 💯 and has a huge potential.


- [ ] asides all of the requested changes i must commend you for your efforts on working on your project and i ask that you take your time to implement before you resubmit another review request. :+1: 
- [ ] also try adding a descriptive pr summary detailing all of the changes you have made.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-30 06:59 UTC, Efiamotu-1 commented on style.css
> +
- @Fernando426 i will like to explain a few things to you and then profer solutions to guide you in solving the issues the previous reviewers spotted and requested changes 
- [ ] Firstly what you are meant to do in this milestone is to create your portfolio using mobile first approach and to do that it means every single styling you do in your css is tailored to work on only mobile screens and when it is time to create the design for desktop versions or tablet version you will use these particular media query examples
```
@media screen and (min-width: 768px) {
 // using this suggest that whatever styling you put in this section will only apply to your webpage when it is showing on screen sizes above 768px that is it will apply only to `tablet devices, ipad and desktop devices`.  with this explanation you would see how the mobile first approach works because any thing styled outside of this media section would apply to devices less than 567px such as `mobile phones`
}
```
> - it is worthy to note that whenever you are using media screen with min-width you are employing the mobile first approach but from your css you are making use of `max-width` which suggests that you are not employing the mobile first approach but desktop first approach.
- [ ] Therefore from your implementation in line `154` you will need to change your approach to reflect mobile first design.

2023-04-30 06:59 UTC, Efiamotu-1 commented on index.html
> +  </div>
- [ ] from what i can see here you have necessarily created two headers and two navigations. now from looking at your code base (Css styling using media query) the reason you are doing this is becasue you are not following the mobile first approach because you are trying to show just the hamburger and logo for mobile screens using `max-width` and then you are displaying the `portfolio, about, contact and mail icon` on the desktop version. honestly you are doing above and beyond the milestone requirement because you are not required to begin styling for the desktop version yet. And also you do not need to create two navigation and two headers in your webpage you only need one header and one navigation and with the css property called `display: block` & `display: none` which you will make use of in further milestones you will be able to show the contents of hanburger and texts on different screen sizes. - please @Fernando426 i understand a bit of your struggles and i will indulge you to take your time and go over all i will say in this review and you can also reach out to me on slack for further clarifications if you do not understand my details will be in the pr summary. :grin:  :+1:

2023-04-30 06:59 UTC, Efiamotu-1 commented on index.html
> +    </div>
- [ ] currently you will notice that your images are not displaying, this is becasue the paths you have written in the src for all of your image file is wrong, having looked at how you saved the resources in your project this is the descrepancies
> - current src [ src="./Images/My Logo.png" ]
> - what your src should be [ src="./images/My Logo.png" ]
- [ ] from the above you are making use if capital letter i when in actuality it should be small letter i becasue you saved all your images in a folder name **images** not **Images**
- [ ] please make the correct changes to all of the places where you used an image and you will be able to see all of your icons and images. :+1:

2023-04-30 06:59 UTC, Efiamotu-1 commented on style.css
- [ ] The last reviewer noted that your pages are overflowing because you are making use of fixed width in your project. having looked at your code base this is the case and because of making use of fixed with with pixels `px` on a smaller screen size the webpage is not responsive as it continues to still take the fixed width which you have defined
- [ ] In a number of places you used `375px` which was the width provided on figma, please note that while you are required to copy all of the css properties used in figma for some sections sopying the width could become detrimental as it has happened in your case so my candid advice is that you do not use the fixed width in pixels like `375px` but rather make use of `%` which are responsive or `rem` and `em`. 
- [ ] However to correct the current overflowing nature of your page these are the things to do to make your website mobile friendly.
- [ ] please take note of the things i have said and try to understand what i have explained go online to find some answers and then implement the chages. :+1: :grin:

2023-05-04 01:22 UTC, merged