Set up and adjusted the portfolio projects section
Fernando426/Portfolio-mobile-website pull request #14
Opened 2023-07-06 20:35 UTC by Fernando426

- Set up and adjusted the portfolio projects section
- This is my project from the previous module since I had to repeat the portal. I have been adjusting it and making small improvements

2023-07-06 21:16 UTC, aamirkhan2478 requested changes
Hi @Fernando426, 

![](https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47k5uapdptg00nidbw3qaxx8iqgsusgaswci2c3uh1&rid=giphy.gif&ct=g)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ All linter passed

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-06 21:16 UTC, aamirkhan2478 commented on index.html
https://github.com/Fernando426/Portfolio-mobile-website/blob/c59fd198bbd5dddbc9142c008db79ec06f7174f5/index.html#L130-L153

- [ ] I really appreciate your effort in trying to match your design with the design given 👏. In addition, great job for you have used list tags here 👏. What I would like you to improve on is that, as you see the technology categories("Languages", "Frameworks", "Skills") are list items and it is right but their belongings(for example; Languages list contains "Ruby", "Javascript", etc ) should be nested inside them. Let me show you what I would like you to do by example;

```HTML
<ul>
     <li><h3>Languages</h3>
            <ul>
               <li>Javascript</li>
               <li>Ruby</li>
               <li>Html</li>
               <li>CSS</li>
            </ul>
     </li>
    <li><h3>Frameworks</h3> 
            <ul>        
               <li>React.js</li> 
               <li>Ruby on Rails</li> 
               <li>RSpec</li> 
               <li>Capybara</li>
            </ul> 
     </li>
     <li><h3>Skills</h3> 
            <ul>        
               <li>Database Managements</li> 
               <li>Version Control</li> 
               <li>CLI</li> 
               <li>API Design</li>
               <li>Web Development</li>
            </ul> 
      </li>
</ul>
```
This is what I would like you to follow because it is **more logical** and it is among the requirements. It is referred to as **Nesting list into another list**. For more information, please read this [documentation](https://www.webucator.com/article/how-to-properly-nest-lists-in-html/) 💡 😃

2023-07-06 21:16 UTC, aamirkhan2478 commented on style.css
- [ ] Please follow the `DRY` principles to clean your code. The `DRY` principle states that there should be only one copy of important information. `Cascading style sheets` control the appearance of `HTML` documents. By having separate `HTML` and `CSS` files, it is easy and efficient to have several different `HTML` documents with the same general appearance. So kindly remove the repetition from your code like if check your code you use `font-family: Crete Round` in 14 places so it is good to remove all the properties of this `font-family` and create one class whose name is `crete-family` and add `Crete Round` family in this class and then use this class in your HTML where you want to use this `font-family` so its look more clean and organized code check below :point_down: my example

**In CSS**
```CSS
.crete-family{
font-family: 'Crete Round', serif;
}
``` 

**In HTML**
```HTML
<h2 class="subtitle crete-family">My Recent Works</h2>
```

2023-07-07 23:38 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Fernando426  

Your project is complete! Great job for making the changes requested 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- great design
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 23:39 UTC, merged