Setup portfolio mobile website
Fernando426/Portfolio-mobile-website pull request #2
Opened 2023-05-03 08:06 UTC by Fernando426

- Fix the path to the images folder
- Applied the mobile-first approach
- Fix measurement units

2023-05-03 09:05 UTC, Ibizugbe requested changes
Hi @Fernando426 👋👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/235873055-6cb79e46-6def-427b-a74c-a66dfddd14fa.gif)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] Linters are passing👍.
- [x] Github flow have been used👍.
- [x] Content is aligned with flexbox👍.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL] Your commit messages are descriptive and meaningful😉. but we can even make it more professional by ensuring they are capitalized👍.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 09:05 UTC, Ibizugbe commented on index.html
> +  </header>
Nice job on your tool bar👍. but let's try to stick to the [design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1-1471&t=hSlFR5NV8rnV3Jfn-0) as it is a requirement in this milestone😉. Kindly take note of the spacings in your navbar👍.

| Figma design                                                             | Your design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="300" alt="design" src="https://user-images.githubusercontent.com/64643995/235868961-21384f17-82ec-43b0-9596-af7c1ff88793.png">|<img width="300" alt="yours" src="https://user-images.githubusercontent.com/64643995/235869256-dc2de70e-c583-4487-b4b8-ffbb3bae9b68.png">|

2023-05-03 09:05 UTC, Ibizugbe commented on index.html
> +  </main>
Nice job on your headline section👍👍. Let's ensure to stick to the design as it is a requirement in this milestone👍Kindly take note of the positioning of the background image😉, currently yours is not properly positioned and it makes it hard to read some texts😉. Kindly see how the image is positioned in the design and make the necessary changes👍. Also take note of the spacings between the social icons😉

| Your design                                                             | Figma design                                         |
| --------------------------------------------------------------------------------| --------------------------------------------------------- |
|<img width="300" alt="yours" src="https://user-images.githubusercontent.com/64643995/235872371-e38566a0-a290-4c0b-982c-3c3f9389471f.png">|<img width="300" alt="design" src="https://user-images.githubusercontent.com/64643995/235872449-95e3f2e4-4fe1-413b-b8df-1b9575417aac.png">|

2023-05-03 10:11 UTC, Fernando426 commented on index.html
> +  </header>
![re2](https://user-images.githubusercontent.com/84606026/235885210-e3ea2e5b-1708-4054-813a-0bdfeab1e4e5.png)

Thanks for the review, but I'd appreciate it if you could review a few things, the image you posted for review is missing a chunk at the top. that is why the logo seems to be centered, but, checking it in figma, it is clearly not centered, I checked the figma template and the part of the logo that you pointed out to me, clearly has a much smaller lower margin than the upper one, being the lower margin of of 12px and the upper one of 56mx, I suppose that this upper margin with more space makes sense on the mobile screen, due to the icons of the stack, signal, time, among others. So I'm trying to stick to the model as much as I can. I would like to know exactly what I should do to avoid requesting unnecessary revisions, because they are very limited!
I would appreciate any collaboration and clarification to be able to satisfactorily finish this part of the project and be able to continue advancing. thank you!

2023-05-03 10:17 UTC, Fernando426 commented on index.html
> +  </main>
![375](https://user-images.githubusercontent.com/84606026/235889159-d1389dd0-e670-4fb1-ad1b-951aecbdafd4.JPG)
I have been reviewing my project, testing the different resolutions and I can't find any that shows me the model with the image at that height, I have attached a screenshot of my project with both mobile and desktop resolutions. Could you please tell me what resolution is that that you show me in the review?
Thank you!

2023-05-03 23:39 UTC, Fernando426 commented
- Greetings, I have corrected the size of my nav-var, and I have also corrected my image position and responsive settings.

2023-05-04 00:06 UTC, taldr27 commented on index.html
> +  </main>
Great job! I tested it with a `(375x720)` and it looks fantastic! Keep up the good work! 💯

2023-05-04 00:06 UTC, taldr27 commented on index.html
> +  </header>
Hello @Fernando426, thank you for submitting your project. I appreciate the effort you put into it. I noticed that you did a great job applying the suggestion to adjust the `margins` of the logo. I apologize for the delayed response to your question. After reviewing the Figma template, it seems that the larger upper margin makes sense for the mobile screen because of the icons of the stack, signal, and time, among others. Therefore, you can omit the extra space of those phone icons, and the logo will be centered. 🎯

2023-05-04 00:08 UTC, taldr27 approved these changes
# Status: Approved! 🟢 
Hi @Fernando426, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif)

## Highlights 🎉 
✅ Professional and customized README. 
✅ Linters tests passing. 👍
✅ Correct use of GitHub Flow.
✅ Nice work with your design! 🎯
✅ Incorporates feedback from previous code reviews.🤓
✅ Pull request has a descriptive title and summary.

-----
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-05-04 01:22 UTC, merged